### ISSUE TITLE
Roadmap.

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/timezone-tracker#1]
- [ ] Getting dynamic times to work properly.
- [ ] Storing the database in a different place across operating systems.
- [ ] Manual scrolling through data.

**Comment by Xithrius** [comment]
The [roadmap project](https://github.com/Xithrius/timezone-tracker/projects/1) will be used for tracking instead.
